spring.application.name=boleto-api

server.port=8085

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:boletodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger-ui.html